# Generated by Django 4.2 on 2023-11-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asio', '0002_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
