# Generated by Django 4.2 on 2023-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asio', '0003_alter_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sitc2',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='value',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='yeardata',
            name='year',
            field=models.BigIntegerField(default=0),
        ),
    ]
