# Generated by Django 2.2 on 2023-08-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, upload_to='home_images')),
                ('front_text', models.CharField(blank=True, max_length=100)),
                ('middle_text', models.CharField(blank=True, max_length=100)),
                ('last_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
