# Generated by Django 2.2 on 2023-08-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0002_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
    ]
