# Generated by Django 4.2 on 2023-09-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0003_auto_20230829_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('profile', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=40, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.ImageField(blank=True, upload_to='bio_images')),
            ],
            options={
                'verbose_name_plural': 'Biography',
            },
        ),
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signupuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='signupuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
