# Generated by Django 4.2 on 2023-09-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0004_biography_alter_home_id_alter_signupuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('percentage', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Skills',
            },
        ),
    ]
