# Generated by Django 4.2 on 2023-09-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0009_alter_skills_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='service_images')),
                ('service', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
