# Generated by Django 4.2 on 2023-09-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0010_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id'], 'verbose_name_plural': 'Services'},
        ),
    ]
