# Generated by Django 4.2 on 2023-09-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0011_alter_services_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='portfolio_images')),
                ('header_four', models.CharField(blank=True, max_length=30)),
                ('italics', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Portfolio',
                'ordering': ['id'],
            },
        ),
    ]
