# Generated by Django 4.2 on 2023-10-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0013_portfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, choices=[('app', 'App'), ('card', 'Card'), ('web', 'Web')], max_length=30),
        ),
    ]
