# Generated by Django 4.2 on 2023-11-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brenda', '0016_alter_testimonial_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Contact',
                'ordering': ['id'],
            },
        ),
    ]
