# Generated by Django 4.2 on 2024-04-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('guessed_letters', models.CharField(default='', max_length=150)),
                ('max_attempts', models.IntegerField(default=6)),
                ('attempts_left', models.IntegerField(default=6)),
            ],
        ),
    ]
