# Generated by Django 4.2 on 2024-06-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name_plural': 'Account'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name_plural': 'Loan'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name_plural': 'Transaction'},
        ),
    ]
