# Generated by Django 4.2 on 2023-12-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tab',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='tab',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
