# Generated by Django 4.2 on 2024-02-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabs', '0002_alter_tab_options_tab_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='saved_btn',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
