# Generated by Django 4.2 on 2024-06-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabs',
            options={'ordering': ['id'], 'verbose_name_plural': 'Tabs'},
        ),
    ]
