# Generated by Django 4.2 on 2024-06-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_tabs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabs',
            name='saved_btn',
            field=models.JSONField(null=True),
        ),
    ]
