# Generated by Django 4.2 on 2024-03-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_lname_remove_topic_lang_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='blog.lname'),
        ),
    ]
