# Generated by Django 4.2 on 2024-03-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='blog.lname'),
        ),
    ]
