# Generated by Django 4.2 on 2024-03-27 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_topic_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lname',
            new_name='Languages',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='type',
        ),
        migrations.AddField(
            model_name='topic',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='blog.languages'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
