# Generated by Django 4.2 on 2024-03-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comments_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reply_to',
        ),
    ]
